spring:
  data:
    mongodb:
      database: Carnivry
      uri: mongodb://localhost:27017/
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      max-file-size: 16MB
      max-request-size: 18MB
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 300000
server:
  port: 5300
  error:
    include-message: always

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

